### ISSUE TITLE
Make a routine to read SI_ALIGN from a characteristics file

### ISSUE THREAD

**Issue by jeanconn** [sot/aimpoint_mon#6]
It would be handy for starcheck to have a method exposed to just get the SI_ALIGN from the file that has already been made.

**Comment by taldcroft** [comment]
Can this just go into Ska.ParseCM?  This is essentially a very limited parser for CHARACTERISTICS (only reads ODB_SI_ALIGN).

**Comment by jeanconn** [comment]
Sure.  My only thought with having it near update_charateristics in aimpoint_mon was that you could share code and read out the references values with the same code.

**Comment by jeanconn** [comment]
Moved to:

https://github.com/sot/Ska.ParseCM/issues/1
