### ISSUE TITLE
Put calc_si_align someplace starcheck can get to it

### ISSUE THREAD

**Issue by jeanconn** [sot/aimpoint_mon#7]

**Comment by taldcroft** [comment]
Does starcheck need anything more than this?
```
calc_pcad_from_targ(ra_targ, dec_targ, roll_targ, y_off, z_off, si_align=ODB_SI_ALIGN):
```
If that is all then this could fit into Ska.quatutil perhaps?

**Comment by jeanconn** [comment]
Ska.quatutil sounds fine reasonable.  Also, we don't really have roll_targ, right?  Would you want to transform the PCAD attitude to get the roll and then run this to get the PCAD attitude again?  

Or, while it makes sense to spec this as a "check PCAD" attitude method, would it be just as reasonable to very target coordinates or offsets from the PCAD attitude? (I think that keeps us all at least in one reference frame).

**Comment by taldcroft** [comment]
Good point that we should implement the converse function `calc_targ_from_pcad()`, and that would be the formally correct way to do the verification.

Your idea about transforming the PCAD attitude to get the roll would be correct, but it is a bit circular and you are guaranteed to match in roll.  Thus there is no need to even test roll and instead just use the RA and Dec output of  `calc_targ_from_pcad` to match the OR RA, Dec

**Comment by jeanconn** [comment]
Will do.  Thanks

(Though you do confuse me a bit with "you are guaranteed to match in roll", as yes, if you transform twice you should get your PCAD roll back again, but the target roll and pcad roll are different.)

**Comment by taldcroft** [comment]
Yes, the check is effectively transforming twice (once to get `targ_roll` and then once getting back to `pcad_roll`).

BTW, however you generated the last comment ended up giving me two messages in my inbox.  Reply-all?  Bug in github?

**Comment by jeanconn** [comment]
(No explanation for the two messages.  Pretty sure I replied on github, but I go back and forth).

**Comment by jeanconn** [comment]
If we put this into Ska.quatutil as a not-just-starcheck routine, should the si_align for the routine have a default value?  And if so, should it be fixed or set to follow the values in aimpoint_mon?

**Comment by taldcroft** [comment]
My plan is to take care of this and all the aimpoint / characteristics related actions.  I'll say uncle as needed.

**Comment by jeanconn** [comment]
OK!  I had made a reader for Ska.ParseCM.  I'll put the branch up and you can chuck it as needed.

**Comment by taldcroft** [comment]
Done in https://github.com/sot/chandra_aca/pull/1.
